export DISCOURSE_ADDRESS=""
export DISCOURSE_API_KEY=""
export DISCOURSE_API_USER=""
export DISCOURSE_TOPIC=""
env | grep -e DISCOURSE_ADDRESS -e DISCOURSE_API_KEY -e DISCOURSE_API_USER -e DISCOURSE_TOPIC